/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog.gui.comp;

import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import prog.Sys;
import prog.core.index.Index;
import prog.core.index.IndexBuilder;
import prog.gui.util.FWorker;

/**
 *
 * @author mg31
 */
public class PanelRunning extends javax.swing.JPanel {

    
private JDialog dialog;
private FWorker worker;
    
    public PanelRunning(JDialog dialog) {
        initComponents();
        this.dialog=dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        jbCancel = new javax.swing.JButton();

        jta.setEditable(false);
        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane1.setViewportView(jta);

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jbCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        worker.interrupt();
        dialog.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

public JTextArea textArea(){return jta;}
public void setWorker(FWorker worker){ this.worker=worker; }
    
public void appendText(String l){
    jta.append(l+"\n");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JTextArea jta;
    // End of variables declaration//GEN-END:variables


    

public static void main(String[] args) throws Exception { //debug 
    String fa = Sys.DIR+"/file/TCGA-AB-2812_1.fq.gz";
    String fb = Sys.DIR+"/file/TCGA-AB-2812_2.fq.gz";
    String tag = "test";
    Index index = IndexBuilder.read(Sys.DIR+"/file/index.ind");
    
    JDialog d = new JDialog();
    PanelRunning pan = new PanelRunning(d);
    d.setContentPane(pan);
    d.setSize( new Dimension(600,350) );
    d.setVisible(true);
    
    for( int i=0; i<100; i++ ){
        pan.appendText("line "+i);
        Thread.sleep(500);
    }
    
}

}
